This is an example of a regular ordered list in Asciidoc with no specifiers.

.Source code
[source]
....
. First level
. First level
.. Second level
... Third level
... Third level
.... Fourth level
.... Fourth level
.... Fourth level
... Third level
.. Second level
.. Second level
. First level
....

which renders as:

. First level
. First level
.. Second level
... Third level
... Third level
.... Fourth level
.... Fourth level
.... Fourth level
... Third level
.. Second level
.. Second level
. First level


This is an example of a regular ordered list in Asciidoc using *specific symbols* to change the list style:

.Source code
[source]
....
[loweralpha]
. First level
. First level
[decimal]
.. Second level
[loweralpha]
... Third level
... Third level
[lowerroman]
.... Fourth level
.... Fourth level
.... Fourth level
... Third level
.. Second level
.. Second level
. First level
....

which renders as:

[loweralpha]
. First level
. First level
[decimal]
.. Second level
[loweralpha]
... Third level
... Third level
[lowerroman]
.... Fourth level
.... Fourth level
.... Fourth level
... Third level
.. Second level
.. Second level
. First level
